### PR TITLE
few typos

### PR DESCRIPTION
**Pull request by peterthomassen**
Thank you!

### CODE REVIEW

**Comment by paulehoffman** [comment]
These are all good, but I probably won't accept them because the current draft is the one that will be sent to the RFC Editor. Instead, I'll alert the RFC Editor of these so they can make the same edits during their process.

**Comment by peterthomassen** [comment]
Sure. I just wanted to drop them in case they'd come in useful (you never know which version is the last ...). If not fitting the process, ignore/defer/whatever, no offense taken. (It seemed quicker to edit here than to ask if helpful.)

**Comment by paulehoffman** [comment]
Given that all your edits are correct, I'm pretty sure the RFC Editor will appreciate them!

**Comment by paulehoffman** [comment]
I am closing this PR, but am pointing the RFC Editor to it so they can see it when they edit.

**Pull request closed without merging**
